### ISSUE TITLE
MAP2 data range from large-scale products missing 

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/PDS-Pipelines-Frontends#1]
For large-scale (high-resolution maps), like:
https://astrogeology.usgs.gov/search/map/Mars/MarsScienceLaboratory/Mosaics/MSL_Gale_DEM_Mosaic_10m
the extent is being sent but I assume the variable is truncating the values or ...? Also I can't even type in the values and run since the user-box values also get truncated.

![MAP2_extentError](https://user-images.githubusercontent.com/3095138/56311987-14e7a680-6104-11e9-9e99-7f7b00ecce98.JPG)

![MAP2_extentError_webcode](https://user-images.githubusercontent.com/3095138/56312001-19ac5a80-6104-11e9-973f-f2f004a15c57.JPG)

**Comment by dpmayerUSGS** [comment]
I think this is a priority issue because it means that a core function of the MAP2 submission interface is broken in a way that prevents users from successfully submitting jobs.
