### ISSUE TITLE
for POW, more error tolerant hitting bad images

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/PDS-Pipelines-Frontends#12]
Currently POW stops processing if it hits one corrupt image. Report failed image to user (or log) and continue.

**Comment by dpmayerUSGS** [comment]
Duplicate of https://github.com/USGS-Astrogeology/PDS-Pipelines/issues/387
Fixed in https://github.com/USGS-Astrogeology/PDS-Pipelines/issues/394
